version: '3.1'

volumes:
  Shazam-db:
  Shazam-songs:

services:
  Shazam:
    image: 'Shazam'
    restart: unless-stopped
    ports:
      - 8080:5000

    environment:
      DB_TYPE: ${DB_TYPE:-sqlite}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-Shazam}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-27017}

      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8080}

    build:
      context: .
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8080}

    volumes:
      - Shazam-db:/home/Shazam/db
      - Shazam-songs:/home/Shazam/songs